name: Pedro's Site Env
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3